### ISSUE TITLE
Define participation in curation (how do you help out with the Principles?)

### ISSUE THREAD

**Issue by justwheel** [sustainers/authentic-participation#4]
# Summary

Provide guidance and suggestions on how someone not involved can get involved with core or periphery work

# Background

Currently I ask people interested in the Principles to introduce themselves on a Discourse thread. Because things are vague and unclear on the Principles, this is not a great call to action. With the current core group of folks we have now, we should do some brainstorming and thinking on how to involve others in core circle discussions and periphery participation to spread the Principles far and wide.

# Details

Some helpful resources to frame this: the [XR Self-Organizing System](https://github.com/jwflory/logbook/blob/master/notes/summaries/self-organizing-system.adoc) and @alnermcgunn's thoughts on [self-obsolescence in Sustain Podcast ep. 19](https://github.com/jwflory/logbook/blob/master/notes/summaries/sustain-e19-allen-gunn-gunner.adoc#self-obsolescence).

Putting out some kickstarter thoughts:

* **Maintenance**: Volunteer committee to review changes and proposals to Principles
    * Helpful but this also requires a governance conversation, not sure if we're there yet :grimacing: 
* **Advocacy**: Champion the Principles by bringing them to your org and encouraging internal adoption
* **Design**: Useful design resources for promoting the Principles would be cool
    * Also a helpful way to include designers as contributors, although might need to make some accommodations for inclusivity
* **Promotion**: Creating copy+paste definitions to include in a README/CONTRIBUTING guidelines file (?)

# Outcome

Decentralized model that includes more people in the design and outreach work for the Principles of Authentic Participation

**Comment by jdorfman** [comment]
Added a link to your show notes on https://sustain.codefund.fm/19 

![image](https://user-images.githubusercontent.com/398230/78084063-18ebf300-736c-11ea-993f-2fb3ebe90fbc.png)

**Comment by justwheel** [comment]
@jdorfman Thanks! :smile:

**Comment by justwheel** [comment]
So, per latest discussions, I think this work will manifest as the Advocate Kit we have talked about in the Fireside Chats and on the Discourse forum. I will open a new issue for that, since it is more specific and measurable than this issue.
